repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--select, I, --fix]
      - id: ruff-format
        types_or: [python, pyi]
        args: [--line-length=79]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.8
    hooks:
      - id: uv-lock
