[project]
name = "scroll-accelerator"
version = "0.1.0"
description = "Mouse scroll wheel acceleration in user space."
authors = [
    { name = "albertz", email = "albzey@gmail.com" },
    { name = "Valmiki Kothare", email = "valmikikothare@gmail.com" },
    { name = "eeriemyxi", email = "eeriemyxi@gmail.com" },
]
readme = "README.md"
maintainers = [
    { name = "albertz", email = "albzey@gmail.com" },
    { name = "Valmiki Kothare", email = "valmikikothare@gmail.com" },
]
requires-python = ">= 3.7"
dependencies = ["appdirs", "pynput", "pyyaml"]

[project.scripts]
scroll-accelerator = "scroll_accelerator.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 120
target-version = ["py37"]
